# @package _global_

defaults:
  - _self_
  - data: tofu
  - data_mode: paperconfig_forget01
  - model: tofu-llama-2
  - model_mode: uld_paperconfig
 # - model_mode: full # Not an option in the directory (either 'base','offset' or 'uld') but was initially the default in this config..
  - unlearn_loss: remember+uniform_paperconfig

trainer:
  batch_size: 32
  gradient_accumulation_steps: 4
  max_epochs: 10
  learning_rate: 1e-3
  warmup_ratio: 0.1
  weight_decay: 0.01
  seed: 42
  strategy: gpu
  # strategy: deepspeed

project: debug
name: null #! Set at runtime
debug: false
resume: false
postfix: ""
base_logdir: null #! Set at runtime
seed: 42

save_dir: outputs/model_dir/
BASELOGDIR: "outputs/tune_log"
OUTPUTMODELDIR: "output_directory"

hydra:
  run:
    dir: ${BASELOGDIR}/${hydra.job.name}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys: 
          - save_dir
          - BASELOGDIR
          - OUTPUTMODELDIR
          - data
          - data.conv_template
          - trainer.*
          - model
